# Generated by Django 2.0.5 on 2018-05-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
