# Generated by Django 2.0.5 on 2018-06-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_pub_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_text',
        ),
    ]
